#!/usr/bin/env zsh

# function to show the $PATH line by line
show-path () {
  # convert Zsh's space-delimited `$path` into a newline-delimited `(F)` array
  # https://zsh.sourceforge.io/Doc/Release/Expansion.html#Parameter-Expansion-Flags
  <<<${(F)path}
}

